image: docker:latest

services:
  - docker:dind

stages:
  - build
  - test
  - deploy

before_script:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASS" registry.gitlab.com

build:
  stage: build
  only:
    - master
    - dev
  script:
    - docker pull registry.gitlab.com/labxp2018/smped-front:latest
    - docker build --cache-from registry.gitlab.com/labxp2018/smped-front:latest -t registry.gitlab.com/labxp2018/smped-front:latest .
    - docker push registry.gitlab.com/labxp2018/smped-front:latest

# Test
test:
  stage: test
  script:
    - docker run --rm registry.gitlab.com/labxp2018/smped-front:latest npm test

# Deploy
deploy-front:
  stage: deploy
  only:
    - master
    - dev
  #when: manual
  script:
    - docker pull registry.gitlab.com/labxp2018/smped-front:latest
    - docker build
      --cache-from registry.gitlab.com/labxp2018/smped-front:latest
      -t "registry.gitlab.com/labxp2018/smped-front" .
      - docker push registry.gitlab.com/labxp2018/smped-front
